CREATE TABLE IF NOT EXISTS `countries` (
    `code` VARCHAR(3) KEY NOT NULL,
    `name` VARCHAR(35) NOT NULL,
    `continent_name` VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `players` (
    `id` INT(10) KEY AUTO_INCREMENT,
    `full_name` VARCHAR(50) NOT NULL,
    `nationality` VARCHAR(3) NOT NULL,
    `date_of_birth` DATETIME NOT NULL, 
    `birth_country` VARCHAR(3) NOT NULL,
    `name` VARCHAR(20) NOT NULL,
    `jarsey_number` INT(3) NOT NULL,
    `current_team` INT(5) NOT NULL,
    `last_team` INT(5) NOT NULL,
    `position` VARCHAR(20) NOT NULL,
    `appearances` INT(5) NOT NULL, 
    `goals` INT(5) NOT NULL,
    `image` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `teams` (
    `id` INT(8) KEY AUTO_INCREMENT,
    `name` VARCHAR(20) NOT NULL,
    `full_name` VARCHAR(50) NOT NULL,
    `ground` VARCHAR(30) NOT NULL,
    `logo` VARCHAR(255) NOT NULL,
    `website` VARCHAR(50) NOT NULL,
    `league` INT(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `teams` (`name`, `full_name`, `ground`, `logo`, `website`, `league`) VALUES 
('Real Madrid', 'Real Madrid Club de Fútbol', 'Santiago Bernabéu', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/800px-Real_Madrid_CF.svg.png', 'https://www.realmadrid.com/', 3), 
('Manchester City', 'Manchester City Football Club', 'City of Manchester Stadium', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/360px-Manchester_City_FC_badge.svg.png', 'https://www.mancity.com/', 2), 
('Bayern Munich', 'Fußball-Club Bayern München e. V.', 'Allianz Arena', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/360px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png', 'https://fcbayern.com/en', 1), 
('Internazionale', 'Football Club Internazionale Milano', 'Giuseppe Meazza', 'assets/images/teams/FC_Internazionale_Milano_2021.png', 'https://www.inter.it/en', 4), 
('Juventus', 'Juventus Football Club S.p.A.', 'Juventus Stadium', 'assets/images/teams/Juventus_FC_icon.png', 'http://www.juventus.com/', 4), 
('Manchester United', 'Manchester United Football Club', 'Old Trafford', 'assets/images/teams/Manchester_United_FC_crest.png', 'https://www.manutd.com/', 2), 
('Liverpool', 'Liverpool Football Club', 'Anfield', 'assets/images/teams/Liverpool_FC.png', 'https://www.liverpoolfc.com/', 2), 
('Arsenal', 'The Arsenal Football Club', 'Emirates Stadium', 'assets/images/teams/Arsenal_FC.png', 'https://www.arsenal.com/', 2);

CREATE TABLE IF NOT EXISTS `leagues` (
    `id` INT(8) KEY AUTO_INCREMENT,
    `name` VARCHAR(15) NOT NULL,
    `country` VARCHAR(3) NOT NULL,
    `number_of_team` INT(2) NOT NULL,
    `logo` VARCHAR(255) NOT NULL,
    `website` VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `countries` (`code`, `name`, `continent_name`) VALUES 
('ALG', 'Algeria', 'CAF'),
('EGY', 'Egypt', 'CAF'),
('LBY', 'Libya', 'CAF'),
('MAR', 'Morocco', 'CAF'),
('TUN', 'Tunisia', 'CAF'),
('BEN', 'Benin', 'CAF'),
('BFA', 'Burkina Faso', 'CAF'),
('CPV', 'Cape Verde', 'CAF'),
('GAM', 'Gambia', 'CAF'),
('GHA', 'Ghana', 'CAF'),
('GUI', 'Guinea', 'CAF'),
('GNB', 'Guinea-Bissau', 'CAF'),
('CIV', 'Ivory Coast', 'CAF'),
('LBR', 'Liberia', 'CAF'),
('MLI', 'Mali', 'CAF'),
('MTN', 'Mauritania', 'CAF'),
('NIG', 'Niger', 'CAF'),
('NGA', 'Nigeria', 'CAF'),
('SEN', 'Senegal', 'CAF'),
('SLE', 'Sierra Leone', 'CAF'),
('TOG', 'Togo', 'CAF'),
('CMR', 'Cameroon', 'CAF'),
('CTA', 'Central African Republic', 'CAF'),
('CHA', 'Chad', 'CAF'),
('CGO', 'Congo', 'CAF'),
('COD', 'DR Congo', 'CAF'),
('EQG', 'Equatorial Guinea', 'CAF'),
('GAB', 'Gabon', 'CAF'),
('STP', 'So Tom and Prncipe', 'CAF'),
('BDI', 'Burundi', 'CAF'),
('DJI', 'Djibouti', 'CAF'),
('ERI', 'Eritrea', 'CAF'),
('ETH', 'Ethiopia', 'CAF'),
('KEN', 'Kenya', 'CAF'),
('RWA', 'Rwanda', 'CAF'),
('SOM', 'Somalia', 'CAF'),
('SSD', 'South Sudan', 'CAF'),
('SDN', 'Sudan', 'CAF'),
('TAN', 'Tanzania', 'CAF'),
('UGA', 'Uganda', 'CAF'),
('ZAN', 'Zanzibar', 'CAF'),
('ANG', 'Angola', 'CAF'),
('BOT', 'Botswana', 'CAF'),
('COM', 'Comoros', 'CAF'),
('SWZ', 'Eswatini', 'CAF'),
('LES', 'Lesotho', 'CAF'),
('MAD', 'Madagascar', 'CAF'),
('MWI', 'Malawi', 'CAF'),
('MRI', 'Mauritius', 'CAF'),
('MOZ', 'Mozambique', 'CAF'),
('NAM', 'Namibia', 'CAF'),
('SEY', 'Seychelles', 'CAF'),
('RSA', 'South Africa', 'CAF'),
('ZAM', 'Zambia', 'CAF'),
('ZIM', 'Zimbabwe', 'CAF'),
('REU', 'Runion', 'CAF'),
('BHR', 'Bahrain', 'AFC'),
('IRQ', 'Iraq', 'AFC'),
('JOR', 'Jordan', 'AFC'),
('KUW', 'Kuwait', 'AFC'),
('LIB', 'Lebanon', 'AFC'),
('OMA', 'Oman', 'AFC'),
('PLE', 'Palestine', 'AFC'),
('QAT', 'Qatar', 'AFC'),
('KSA', 'Saudi Arabia', 'AFC'),
('SYR', 'Syria', 'AFC'),
('UAE', 'United Arab Emirates', 'AFC'),
('YEM', 'Yemen', 'AFC'),
('AFG', 'Afghanistan', 'AFC'),
('IRN', 'Iran', 'AFC'),
('KGZ', 'Kyrgyzstan', 'AFC'),
('TJK', 'Tajikistan', 'AFC'),
('TKM', 'Turkmenistan', 'AFC'),
('UZB', 'Uzbekistan', 'AFC'),
('BAN', 'Bangladesh', 'AFC'),
('BHU', 'Bhutan', 'AFC'),
('IND', 'India', 'AFC'),
('MDV', 'Maldives', 'AFC'),
('NEP', 'Nepal', 'AFC'),
('PAK', 'Pakistan', 'AFC'),
('SRI', 'Sri Lanka', 'AFC'),
('CHN', 'China PR', 'AFC'),
('GUM', 'Guam', 'AFC'),
('HKG', 'Hong Kong', 'AFC'),
('JPN', 'Japan', 'AFC'),
('PRK', 'Korea DPR', 'AFC'),
('KOR', 'South Korea', 'AFC'),
('MAC', 'Macau', 'AFC'),
('MNG', 'Mongolia', 'AFC'),
('NMI', 'Northern Mariana Islands', 'AFC'),
('TPE', 'Chinese Taipei', 'AFC'),
('AUS', 'Australia', 'AFC'),
('BRU', 'Brunei', 'AFC'),
('CAM', 'Cambodia', 'AFC'),
('IDN', 'Indonesia', 'AFC'),
('LAO', 'Laos', 'AFC'),
('MAS', 'Malaysia', 'AFC'),
('MYA', 'Myanmar', 'AFC'),
('PHI', 'Philippines', 'AFC'),
('SIN', 'Singapore', 'AFC'),
('THA', 'Thailand', 'AFC'),
('TLS', 'Timor-Leste', 'AFC'),
('VIE', 'Vietnam', 'AFC'),
('ALB', 'Albania', 'UEFA'),
('AND', 'Andorra', 'UEFA'),
('ARM', 'Armenia', 'UEFA'),
('AUT', 'Austria', 'UEFA'),
('AZE', 'Azerbaijan', 'UEFA'),
('BLR', 'Belarus', 'UEFA'),
('BEL', 'Belgium', 'UEFA'),
('BIH', 'Bosnia and Herzegovina', 'UEFA'),
('BUL', 'Bulgaria', 'UEFA'),
('CRO', 'Croatia', 'UEFA'),
('CYP', 'Cyprus', 'UEFA'),
('CZE', 'Czech Republic', 'UEFA'),
('DEN', 'Denmark', 'UEFA'),
('ENG', 'England', 'UEFA'),
('EST', 'Estonia', 'UEFA'),
('FRO', 'Faroe Islands', 'UEFA'),
('FIN', 'Finland', 'UEFA'),
('FRA', 'France', 'UEFA'),
('GEO', 'Georgia', 'UEFA'),
('GER', 'Germany', 'UEFA'),
('GIB', 'Gibraltar', 'UEFA'),
('GRE', 'Greece', 'UEFA'),
('HUN', 'Hungary', 'UEFA'),
('ISL', 'Iceland', 'UEFA'),
('ISR', 'Israel', 'UEFA'),
('ITA', 'Italy', 'UEFA'),
('KAZ', 'Kazakhstan', 'UEFA'),
('KOS', 'Kosovo', 'UEFA'),
('LVA', 'Latvia', 'UEFA'),
('LIE', 'Liechtenstein', 'UEFA'),
('LTU', 'Lithuania', 'UEFA'),
('LUX', 'Luxembourg', 'UEFA'),
('MLT', 'Malta', 'UEFA'),
('MDA', 'Moldova', 'UEFA'),
('MNE', 'Montenegro', 'UEFA'),
('NED', 'Netherlands', 'UEFA'),
('MKD', 'North Macedonia', 'UEFA'),
('NIR', 'Northern Ireland', 'UEFA'),
('NOR', 'Norway', 'UEFA'),
('POL', 'Poland', 'UEFA'),
('POR', 'Portugal', 'UEFA'),
('IRL', 'Republic of Ireland', 'UEFA'),
('ROU', 'Romania', 'UEFA'),
('RUS', 'Russia', 'UEFA'),
('SMR', 'San Marino', 'UEFA'),
('SCO', 'Scotland', 'UEFA'),
('SRB', 'Serbia', 'UEFA'),
('SVK', 'Slovakia', 'UEFA'),
('SVN', 'Slovenia', 'UEFA'),
('ESP', 'Spain', 'UEFA'),
('SWE', 'Sweden', 'UEFA'),
('SUI', 'Switzerland', 'UEFA'),
('TUR', 'Turkey', 'UEFA'),
('UKR', 'Ukraine', 'UEFA'),
('WAL', 'Wales', 'UEFA'),
('CAN', 'Canada', 'CONCACAF'),
('MEX', 'Mexico', 'CONCACAF'),
('USA', 'United States', 'CONCACAF'),
('BLZ', 'Belize', 'CONCACAF'),
('CRC', 'Costa Rica', 'CONCACAF'),
('SLV', 'El Salvador', 'CONCACAF'),
('GUA', 'Guatemala', 'CONCACAF'),
('HON', 'Honduras', 'CONCACAF'),
('NCA', 'Nicaragua', 'CONCACAF'),
('PAN', 'Panama', 'CONCACAF'),
('AIA', 'Anguilla', 'CONCACAF'),
('ATG', 'Antigua and Barbuda', 'CONCACAF'),
('ARU', 'Aruba', 'CONCACAF'),
('BAH', 'Bahamas', 'CONCACAF'),
('BRB', 'Barbados', 'CONCACAF'),
('BER', 'Bermuda', 'CONCACAF'),
('BOE', 'Bonaire', 'CONCACAF'),
('VGB', 'British Virgin Islands', 'CONCACAF'),
('CAY', 'Cayman Islands', 'CONCACAF'),
('CUB', 'Cuba', 'CONCACAF'),
('CUW', 'Curaao', 'CONCACAF'),
('DMA', 'Dominica', 'CONCACAF'),
('DOM', 'Dominican Republic', 'CONCACAF'),
('GUF', 'French Guiana', 'CONCACAF'),
('GRN', 'Grenada', 'CONCACAF'),
('GLP', 'Guadeloupe', 'CONCACAF'),
('GUY', 'Guyana', 'CONCACAF'),
('HAI', 'Haiti', 'CONCACAF'),
('JAM', 'Jamaica', 'CONCACAF'),
('MTQ', 'Martinique', 'CONCACAF'),
('MSR', 'Montserrat', 'CONCACAF'),
('PUR', 'Puerto Rico', 'CONCACAF'),
('SKN', 'Saint Kitts and Nevis', 'CONCACAF'),
('LCA', 'Saint Lucia', 'CONCACAF'),
('SMN', 'Saint Martin', 'CONCACAF'),
('VIN', 'Saint Vincent and the Grenadines', 'CONCACAF'),
('SMA', 'Sint Maarten', 'CONCACAF'),
('SUR', 'Suriname', 'CONCACAF'),
('TRI', 'Trinidad and Tobago', 'CONCACAF'),
('TCA', 'Turks and Caicos Islands', 'CONCACAF'),
('VIR', 'U.S. Virgin Islands', 'CONCACAF'),
('ASA', 'American Samoa', 'OFC'),
('COK', 'Cook Islands', 'OFC'),
('FIJ', 'Fiji', 'OFC'),
('KIR', 'Kiribati', 'OFC'),
('NCL', 'New Caledonia', 'OFC'),
('NZL', 'New Zealand', 'OFC'),
('PNG', 'Papua New Guinea', 'OFC'),
('SAM', 'Samoa', 'OFC'),
('SOL', 'Solomon Islands', 'OFC'),
('TAH', 'Tahiti', 'OFC'),
('TGA', 'Tonga', 'OFC'),
('TUV', 'Tuvalu', 'OFC'),
('VAN', 'Vanuatu', 'OFC'),
('ARG', 'Argentina', 'CONMEBOL'),
('BOL', 'Bolivia', 'CONMEBOL'),
('BRA', 'Brazil', 'CONMEBOL'),
('CHI', 'Chile', 'CONMEBOL'),
('COL', 'Colombia', 'CONMEBOL'),
('ECU', 'Ecuador', 'CONMEBOL'),
('PAR', 'Paraguay', 'CONMEBOL'),
('PER', 'Peru', 'CONMEBOL'),
('URU', 'Uruguay', 'CONMEBOL'),
('VEN', 'Venezuela', 'CONMEBOL');


INSERT INTO `leagues` (`name`, `country`, `number_of_team`, `logo`, `website`) VALUES
('Bundesliga', 'GER', 18, 'assets/images/leagues/bundesliga_logo.png', 'https://www.bundesliga.com/'),
('Premier League', 'ENG', 20, 'assets/images/leagues/premier_league_logo.png', 'https://www.premierleague.com/'),
('La Liga', 'ESP', 20, 'assets/images/leagues/la_liga_logo.png', 'https://www.laliga.com/'),
('Serie A', 'ITA', 20, 'assets/images/leagues/serie_a_logo.png', 'https://www.legaseriea.it/');